---
title: "Math564_Pilot"
author: "Chenjie Li"
date: "November 1, 2018"
output: pdf_document
---

```{r}
raw <- read.csv('/home/chenjie/Desktop/Math564Project/12_players.csv')
```

```{r}
md_total <-lm(raw$win_ratio~ raw$team_PER,data = raw)
summary(md_total)
plot(raw$team_PER,raw$win_ratio,xlab = 'team_PER', ylab = 'win_ratio', main = '2014 - 2017 Win_Ratio against team_PER - 12 Players') + abline(md_total)+text(win_ratio~ team_PER, labels=raw$team,data=raw, cex=0.3,pos = 4)
```

```{r}
data14<- raw[raw$season ==2014,]
md14 <-lm(data14$win_ratio~ data14$team_PER,data = data14)
summary(md14)
plot(data14$team_PER,data14$win_ratio,xlab = 'team_PER', ylab = 'win_ratio', main = '2014 Win_Ratio against team_PER - 12 Players') + abline(md14)+text(win_ratio~ team_PER, labels=data14$team,data=data14, cex=0.3,pos = 4)
```

```{r}
data15<- raw[raw$season ==2015,]
md15 <-lm(data15$win_ratio~ data15$team_PER,data = data15)
summary(md15)
plot(data15$team_PER,data15$win_ratio,xlab = 'team_PER', ylab = 'win_ratio', main = '2015 Win_Ratio against team_PER - 12 Players') + abline(md15)+text(win_ratio~ team_PER, labels=data15$team,data=data15, cex=0.3,pos = 4)
```

```{r}
data16<- raw[raw$season ==2016,]
md16 <-lm(data16$win_ratio~ data16$team_PER,data = data16)
summary(md16)
plot(data16$team_PER,data16$win_ratio,xlab = 'team_PER', ylab = 'win_ratio', main = '2016 Win_Ratio against team_PER - 12 Players') + abline(md16)+text(win_ratio~ team_PER, labels=data16$team,data=data16, cex=0.3,pos = 4)
```

```{r}
data17<- raw[raw$season ==2017,]
md17 <-lm(data17$win_ratio~ data17$team_PER,data = data17)
summary(md17)
plot(data17$team_PER,data17$win_ratio,xlab = 'team_PER', ylab = 'win_ratio', main = '2017 Win_Ratio against team_PER - 12 Players') + abline(md17)+text(win_ratio~ team_PER, labels=data17$team,data=data17, cex=0.3,pos = 4)
```