---
title: "WinRatio_Age"
author: "Chenjie Li"
date: "November 5, 2018"
output: pdf_document
---

```{r}
age_file = read.csv('/home/chenjie/Desktop/Math564Project/age_winratio.csv')

s14_data <- age_file[age_file$season == 2014,]

s14_md <- lm(s14_data$pct ~ s14_data$avg)

plot(s14_data$avg,s14_data$pct,xlab = 'Team average age', ylab = 'Win ratio', main = '2014 Win_Ratio against team average age') + abline(s14_md)+text(pct~ avg, labels=s14_data$team,data=s14_data, cex=0.3,pos = 4)
```

```{r}
age_file = read.csv('/home/chenjie/Desktop/Math564Project/age_winratio.csv')

s15_data <- age_file[age_file$season == 2015,]

s15_md <- lm(s15_data$pct ~ s15_data$avg)

plot(s15_data$avg,s15_data$pct,xlab = 'Team average age', ylab = 'Win ratio', main = '2015 Win_Ratio against team average age') + abline(s15_md)+text(pct~ avg, labels=s15_data$team,data=s15_data, cex=0.3,pos = 4)
```

```{r}
age_file = read.csv('/home/chenjie/Desktop/Math564Project/age_winratio.csv')

s16_data <- age_file[age_file$season == 2016,]

s16_md <- lm(s16_data$pct ~ s16_data$avg)

plot(s16_data$avg,s16_data$pct,xlab = 'Team average age', ylab = 'Win ratio', main = '2016 Win_Ratio against team average age') + abline(s16_md)+text(pct~ avg, labels=s16_data$team,data=s16_data, cex=0.3,pos = 4)
```

